### ISSUE TITLE
Missing CLOVER folder

### ISSUE THREAD

**Issue by wuyscc** [RyzenPan/Dell-3576-hackintosh-EFI#1]
Hi, I'm using Dell 3576 like you and I'm interesting at Hackintosh. I found your EFI on Gihub but CLOVER folder is empty, can you update that? Thank you very much <3

**Comment by RyzenPan** [comment]
I uploaded the entire EFI zip file separately, which wasn't perfect, but it worked fine

**Comment by wuyscc** [comment]
Thank you very much.

**Comment by RyzenPan** [comment]
I suggest you go to site ”https://blog.daliansky.net/“ 黑果小兵 ,and read more hackintosh knowledge
